### PR TITLE
Zapocet2

### PR DESCRIPTION
**Pull request by xpapulak**
Dobry den,
Posielam opravu zápočtu

### CODE REVIEW

**Comment by ZitaNemeckova** [comment]
* [X] update your branch & resolve conflicts (hint: rebase) (20%) -10% first commit contains weird changes

* [x] reorder commits so that next class-related commits(questions 3, 5, 7) are together (10%)

* [X] squash next class-related commits into one (hint: you should use two `s` not three) (20%) 

* [x] delete commit with question 1 (10%)

* [x] rename commits about your previous experience with Git (questions 2, 4) to be in UPERCASE (hint: you do not rename the commit at the same time as you write r but later) (20%)

* [x] edit commit that mentions SVN so answer is Noooooooooooo or Yesssssssssss (hint: you have to add changed file and amend commit) (20%)

Final score = 90%

**Comment by xpapulak** [comment]
Dobry deň,
Prosím Vás, tento Pull Request bola len tá prvá polovica príkladu ale nemala som conflicts tak som čakala na Vás. Viem že všetky tie body potrebné na zápočet nemám spravené, lebo som sa k nim kvôli tomu ešte nedostala.

**Comment by himdel** [comment]
Dobry den,
tento PR byl otevreny 15 dni beze zmeny a bez jakekoli indikace ze ceka na nas.
Nove hodnoceni jiz bylo odeslano vyucujicim.

Jestli chcete, muzete dokoncit interaktivni rebase, do konce tydne (11.1.), a posleme jim jeste aktualizovanou verzi. Negarantuji ze ji budou respektovat :).

**Comment by xpapulak** [comment]
Dobrý deň,
No ja som vám napísala komentár do pull requestu a aj email.
Ale ďakujem za šancu pošlem Vám to.

Dňa po, 6. jan 2020, 14:52 Martin Hradil <notifications@github.com>
napísal(a):

**Comment by xpapulak** [comment]
Prosím Vás, mohli by ste niečo zmeniť v "Exam" aby som mohla pracovať s konfliktami ? 
Ďakujem

**Comment by himdel** [comment]
@xpapulak Conflict vytvoren :)

**Comment by xpapulak** [comment]
please review @himdel @ZitaNemeckova

**Comment by ZitaNemeckova** [comment]
@xpapulak Updated score :)

**Pull request closed without merging**
